---
title: "Performance_analysis"
author: "LH and KCE"
date: "12/19/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
pacman::p_load(pacman, tidyverse, caret, e1071, stringr, yarrr, 
               wesanderson, patchwork, knitr, kableExtra, magick, webshot)


anon_danlp <- read_csv("../merge_df_no_term.csv", 
                col_types = cols(gender = col_character(),
                                 replacement = col_character()))

anon_danlp_poly <- read_csv("../merge_df_no_term_danlp_polyglot.csv")

anon_danlp <- anon_danlp %>% select(idx_gold, token_gold, idx_deepanon, token_deepanon, ner_gold = corrections, ner_deepanon, ner_ent_n_deepanon, ner_conf_deepanon, coder, filename, row, filepath = filepath_x)

anon_danlp_poly <- anon_danlp_poly %>%  select(ner_gold = corrections, ner_deepanon, ner_conf_deepanon, coder, filepath = filepath_x)


```


# Grouping of tokens
```{r}
anon <- anon_danlp
anon %>% filter(ner_gold == "GPE") %>% select(token_gold) %>% unique() %>% View() #almost exclusively locations (mostly countries)
# e.g. GPE to LOC - also mostly classified as loc (but also alot like ORG)
anon %>% filter(ner_gold == "NAMIT") %>% select(token_gold) %>% unique() %>% View() # seems there is some errors in the category (correct: Ferrari, Mustang, XSI, Google+ Forkert: Bazaar (ikke et named item), 	Sheffield varmblods pony (race ikke named item), ice tea)
# this is also a very fuzzy category we will probably rework it
# e.g. NAMIT to NA
anon %>% filter(ner_gold == "IDNUM") %>% select(token_gold) %>% unique() %>% View() # error the with CVR and tlf being included otherwise fine
anon %>% filter(ner_gold == "LANG") %>% select(token_gold) %>% unique() %>% View() # errors in non-danish being languages (languages include e.g. danish english, not "α" or "عرب")
anon %>% filter(ner_gold == "MON") %>% select(token_gold) %>% unique() %>% View() #OK
anon %>% filter(ner_gold == "PTITLE") %>% select(token_gold) %>% unique() %>% View() #OK
anon %>% filter(ner_gold == "NORP") %>% select(token_gold) %>% unique() %>% View() # Mostly nationalities, but OK with errors
anon %>% filter(ner_gold == "NUM") %>% select(token_gold) %>% unique() %>% View() #OK
anon %>% filter(ner_deepanon == "NUM" & !(ner_gold %in% c("IDNUM", "DATE", "NUM", "MON"))) %>% select(token_gold) %>% unique() %>% View() # only a few missed - but some misses
anon %>% filter(ner_gold == "ORG") %>% select(token_gold) %>% unique() %>% View() #OK
anon %>% filter(ner_gold == "PERS") %>% select(token_gold) %>% unique() %>% View() #OK
anon %>% filter(ner_gold == "USER") %>% select(token_gold) %>% unique() %>% View() # Nogle af disse ser ud til blot at være navne e.g. henriette
anon %>% filter(ner_gold == "WEB") %>% select(token_gold) %>% unique() %>% View() #OK


# Conclusion
  # DATE -> NA
  # EMAIL (stays the same)
  # EVENT -> NA
  # IDNUM -> NUM
  # LANG -> NA
  # NAMIT -> NA
  # GPE -> LOC
  # MON -> NUM however not entirely true (e.g. kr. and DKK is also in MON)
  # NAMIT -> NA
  # NORT -> NA
  # PTITLE -> NA
  # WEB -> NA (for now, men ser ud til at være let at detekte)
mapping_from = c("DATE", "EVENT", "IDNUM", "LANG", "NAMIT", "GPE", "MON", "NORP", "PTITLE", "WEB")
mapping_to   = c("NA",   "NA",    "NUM",   "NA",   "NA",    "LOC", "NUM", "NA",   "NA",     "NA")
```

# Normalization
```{r}
# normalization of tags to deepanon
normalize_df <- function(anon, grouping = T, group_mapping_from = mapping_from, group_mapping_to = mapping_to) {
  
#  anon <- anon %>% 
#    group_by(coder, filepath, idx_deepanon) %>% 
#    summarise_all(first) # test this
  
  # normalization of tags (remove B and I)
  anon <- anon %>% 
    mutate(ner_gold = str_split(ner_gold, "_", simplify = T)[,1],
           ner_deepanon = str_replace(ner_deepanon, ".*-", ""),
           ) 
  
  #Map values
  anon$ner_gold <- anon %>% 
    pull(ner_gold) %>% 
    plyr::mapvalues(., from=c("LO", "NU", "OR", "GP", NA), to=c("LOC", "NUM", "ORG", "GPE", "NA"))
  
  anon$ner_deepanon <- 
    anon %>% pull(ner_deepanon) %>% 
    plyr::mapvalues(., from=c("PER","NUMBER", "MAIL", "E-MAIL", "PRONOUN", "TWITTER", NA), to=c("PERS","NUM", "EMAIL", "EMAIL", "NA", "NA", "NA"))
  
  # Check if anything should be fixed (should be empty)
    # valid_tags = c("NA", "PERS", "NUM", "EVENT", "ORG", "WEB", "NAMIT",
    #                "NORP", "GPE", "DATE", "LOC", "IDNUM", "PTITLE", 
    #                "EMAIL", "USER", "LANG", "MON")
    # unique(anon$ner_gold)[!unique(anon$ner_gold) %in% valid_tags]
    # unique(anon$ner_deepanon)[!unique(anon$ner_deepanon) %in% valid_tags]
  
  if (grouping) {
      anon$ner_gold <- anon %>% 
        pull(ner_gold) %>% 
        plyr::mapvalues(., from=group_mapping_from, 
                           to  =group_mapping_to)

  }
    
  
  anon$ner_gold <- as.factor(anon$ner_gold)
  anon$ner_deepanon <- as.factor(anon$ner_deepanon)
  
  return(anon)
}

```

# Confusion matrices
```{r}
anon_danlp <- normalize_df(anon_danlp)
anon_danlp_poly <- normalize_df(anon_danlp_poly)

#all categories
confusionMatrix(anon_danlp$ner_deepanon, anon_danlp$ner_gold)
confusionMatrix(anon_danlp_poly$ner_deepanon, anon_danlp_poly$ner_gold)


# only for the categories in DaNLP/polyglot
other_class_to_na <- function(anon){
  df <-anon %>% 
    mutate(ner_deepanon = if_else(ner_deepanon %in% c('LOC', 'ORG', 'PERS', 'NA'), ner_deepanon, factor(NA)),
           ner_gold = if_else(ner_gold %in% c('LOC', 'ORG', 'PERS', 'NA'), ner_gold, factor(NA)))
  
  df$ner_deepanon <- as.factor(as.character(df$ner_deepanon))
  df$ner_gold <- as.factor(as.character(df$ner_gold))
  return(df)
}
anon_danlp_na <- other_class_to_na(anon_danlp)
anon_danlp_poly_na <- other_class_to_na(anon_danlp_poly)

# only NER tagger categories
confusionMatrix(anon_danlp_na$ner_deepanon, anon_danlp_na$ner_gold)
confusionMatrix(anon_danlp_poly_na$ner_deepanon, anon_danlp_poly_na$ner_gold) 

# baseline accuracy
sum(anon_danlp_na$ner_gold == 'NA') / nrow(anon_danlp_na)
sum(anon_danlp_poly_na == 'NA') /nrow(anon_danlp_poly_na)
```

# Grouped by filename
```{r}

perf <- function(df, only_one = F){
  "Get all performance measures from confusion matrix to 1 row in a dataframe"
  conf <- caret::confusionMatrix(df$ner_deepanon, df$ner_gold)
  
  by_class <- data.frame(conf$byClass) %>% 
      mutate(class = rownames(.)) %>% 
      gather(var, val, Sensitivity:Balanced.Accuracy) %>% 
      unite(var_new, class, var, sep="_") %>%
      spread(var_new, val) %>% 
      rename_all(funs(str_sub(., 8, -1)))
    
  if(only_one == F){
    overall <- data.frame(file = unique(df$filepath),
                    n_tokens = nrow(df),
                    Accuracy = conf$overall['Accuracy'],
                    acc_low = conf$overall['AccuracyLower'],
                    acc_high = conf$overall['AccuracyUpper'],
                    Kappa = conf$overal['Kappa'],
          
                    row.names = NULL)
  }
  else{
    overall <- data.frame(n_tokens = nrow(df),
                    Accuracy = conf$overall['Accuracy'],
                    acc_low = conf$overall['AccuracyLower'],
                    acc_high = conf$overall['AccuracyUpper'],
                    Kappa = conf$overal['Kappa'],
          
                    row.names = NULL)
  }
  return(cbind(overall, by_class))
}

# looping through all filepaths to get a performance row for each file
get_performance <- function(df){
  i <- 1
  for(file in unique(df$filepath)){
    performance <- df %>% filter(filepath == file) %>% perf(.) 
    if(i == 1){
      perform <- performance
    }
    else{
      perform <- rbind(perform, performance)
    }
    i = i + 1
  }
  return(perform)
}

perform_danlp <- get_performance(anon_danlp_na)
perform_danlp_poly <- get_performance(anon_danlp_poly_na)
```

# Visualizations
```{r}

##### CREATE TABLE TO SEE HOW MANY FILES HAVE TAGS IN EACH CLASS


boxer <- function(df, metrics){
  df %>% 
    select(metrics) %>% 
    gather('metric', 'value') %>% 
    ggplot(aes(metric, value, fill = metric)) +
    geom_boxplot() +
    theme(axis.text.x = element_blank(),
          axis.ticks.x = element_blank())
}

source("R_rainclouds.R")

rainclouder <- function(df, title, main = T){
  n_colors <- length(unique(df$metric))
  
  plot <- df %>% 
  ggplot(aes(x = metric, y = value, fill = metric, colour = metric)) +
  geom_flat_violin(position = position_nudge(x = .3, y = 0), 
                   adjust = 0.5, trim = FALSE)+
  geom_point(position = position_jitter(width = .15), size = .25) +
  geom_boxplot(aes(x = metric , y = value),
               outlier.shape = NA, alpha = 0.3, width = .05,
               position = position_nudge(.25),
               colour = "black") +
  ylab('Score')+xlab('Metric')
  
  if(main == T){
    plot <- plot +
      scale_y_continuous(breaks = c(-0.2, 0, 0.2, 0.4, 0.6, 0.8, 1), 
                     labels = c(-0.2, 0, 0.2, 0.4, 0.6, 0.8, 1),
                     limits = c(-0.3, 1))
  }
  else{
    plot <- plot +
     scale_y_continuous(breaks = c(-0.2, 0, 0.2, 0.4, 0.6, 0.8, 1), 
                     labels = c(-0.2, 0, 0.2, 0.4, 0.6, 0.8, 1),
                     limits = c(0, 1))  
  }
  plot <- plot +
  coord_flip() +
  theme_bw() + 
  guides(fill = FALSE, colour = FALSE) +
  scale_colour_brewer(palette = "Set1")+
  scale_fill_brewer(palette = "Set1")+
  #scale_color_manual(values = wes_palette('Chevalier1', 
  #                                      n = n_colors)) +
  #scale_fill_manual(values = wes_palette('Chevalier1', 
  #                                       n = n_colors)) +
  ggtitle(title)
  if(main == T){
    return(plot)
  }
  else{
    plot <- plot +
      facet_wrap(~class, ncol = 2)
    return(plot)
  }
}

```

# Plots
```{r}

valid_metrics <- c('Balanced.Accuracy', 'Sensitivity', 'Specificity')
overall_metrics <- c('Accuracy', 'Kappa')

# grouping for facet wrapped plots
group_class <- function(df){
  grouped_class <- df %>% 
   # filter(n_tokens >) %>% # test
    select(-c(file, n_tokens, Accuracy, acc_low, acc_high, Kappa)) %>% 
    gather('metric', 'value') %>% 
    mutate(class = sapply(str_split(metric, "_"), function(x) x[1]),
           metric = sapply(str_split(metric, "_"), function(x) x[2])) %>% 
    mutate(metric = factor(metric, levels = 
                             c('Specificity', 'Sensitivity', 'Balanced.Accuracy'))) %>% 
    filter(metric %in% valid_metrics) 
  return(grouped_class)
}
  
grouped_raincloud_danlp <- group_class(perform_danlp) %>% 
  rainclouder('Performance by class - DaNLP', main = F)

grouped_raincloud_danlp_poly <- group_class(perform_danlp_poly) %>% 
  rainclouder('Performance by class - DaNLP + Polyglot', main = F)

overall_rain_danlp <- perform_danlp %>%
  select(overall_metrics) %>% 
  gather('metric', 'value') %>%
  mutate(metric = factor(metric, levels = 
                           c('Kappa', 'Accuracy'))) %>% 
  rainclouder('Overall Performance Metrics - DaNLP')

overall_rain_danlp_poly <- perform_danlp_poly %>% 
  select(overall_metrics) %>% 
  gather('metric', 'value') %>%
  mutate(metric = factor(metric, levels = 
                           c('Kappa', 'Accuracy'))) %>% 
  rainclouder('Overall Performance Metrics - DaNLP + Polyglot')

grouped_raincloud_danlp / grouped_raincloud_danlp_poly
overall_rain_danlp / overall_rain_danlp_poly


```

## Tables
```{r}
keep <- c('Accuracy', 'acc_low', 'acc_high', 
          'LOC_F1', 'LOC_Sensitivity', 'LOC_Specificity', 
          'PERS_F1', 'PERS_Sensitivity', 'PERS_Specificity', 
          'ORG_F1', 'ORG_Sensitivity', 'ORG_Specificity',
          'NA_F1', 'NA_Sensitivity', 'NA_Specificity')


perf_danlp_na <- perf(anon_danlp_na, only_one = T) %>% select(keep) %>% mutate(Model = 'DaNLP_na')
perf_danlp_poly_na <- perf(anon_danlp_poly_na, only_one = T) %>% select(keep) %>% mutate(Model = 'DaNLp + Polyglot_na')

perf_danlp <- perf(anon_danlp, only_one = T) %>% select(keep) %>% mutate(Model = 'DaNLP')
perf_danlp_poly <- perf(anon_danlp_poly, only_one = T) %>% select(keep) %>% mutate(Model = 'DaNLP + Polyglot')

perf_df <- bind_rows(perf_danlp, perf_danlp_poly, perf_danlp_na, perf_danlp_poly_na) %>% 
  gather('metric', 'value', -Model) %>% 
  reshape(timevar="Model",idvar="metric",direction="wide") %>% 
  rename_at(vars(starts_with("value")), 
    funs(str_replace(., "value.", "")))

perf_df %>% kable(., "latex") %>%
  kable_styling(latex_options = "striped") %>%
  save_kable("tabs/test.png")
```


```{r}
### TODO 
# ADD HIT/MISS COLUMN FOR F1 AND PRETTY PLOTS

```

# Uppercase errors - Need grouping
```{r}
anon <- anon_danlp

# correctly classified is upper?
correct_is_upper <- anon %>% 
  filter(as.character(ner_gold) == as.character(ner_deepanon) & (as.character(ner_gold) %in% c("LOC", "PERS", "ORG"))) %>% 
  mutate(is_upper = grepl("^[[:upper:]]", token_gold)) %>% 
  group_by(is_upper) %>% 
  summarise(n = n())
#   is_upper     n
#   <lgl>    <int>
# 1 FALSE       11
# 2 TRUE      1043

# not correctly classified is upper?
notCorrect_is_upper <- anon %>% 
  filter(as.character(ner_gold) != as.character(ner_deepanon) & (as.character(ner_deepanon) %in% c("LOC", "PERS", "ORG"))) %>% 
  mutate(is_upper = grepl("^[[:upper:]]", token_gold)) %>% 
  group_by(is_upper) %>% 
  summarise(n = n()) 
#   is_upper     n
#   <lgl>    <int>
# 1 FALSE      200
# 2 TRUE      2655

# misses are upper?
misses_upper <- anon %>% 
  filter(as.character(ner_gold) != as.character(ner_deepanon) & (as.character(ner_gold) %in% c("LOC", "PERS", "ORG"))) %>% 
  mutate(is_upper = grepl("^[[:upper:]]", token_gold)) %>% 
  group_by(is_upper) %>% 
  summarise(n = n()) 
#   is_upper     n
#   <lgl>    <int>
# 1 FALSE      136
# 2 TRUE      1337
```


# Error by POS-tag
```{r}
# assumes pos tags are correct
```

